import type { Question } from './types';

export const SEED_QUESTIONS: Question[] = [
  // ===== BERHITUNG — Kelas 1, Level 1 =====
  {
    id: 'seed-b-1',
    modul: 'berhitung',
    kelas: 1,
    level: 1,
    tipe_soal: 'pilihan_ganda',
    pertanyaan: '🍎🍎 + 🍎🍎🍎 = berapa apel?',
    pilihan: ['4', '5', '6', '3'],
    jawaban_benar: '5',
    penjelasan: 'Ada 2 apel lalu ditambah 3 apel lagi, jadi total 5 apel.',
  },
  {
    id: 'seed-b-2',
    modul: 'berhitung',
    kelas: 1,
    level: 1,
    tipe_soal: 'pilihan_ganda',
    pertanyaan: 'Ada 7 🐥 di kandang, 2 🐥 pergi. Sisa berapa?',
    pilihan: ['4', '5', '6', '3'],
    jawaban_benar: '5',
    penjelasan: 'Dari 7 anak ayam, 2 pergi, sisanya 5.',
  },
  {
    id: 'seed-b-3',
    modul: 'berhitung',
    kelas: 1,
    level: 1,
    tipe_soal: 'pilihan_ganda',
    pertanyaan: '⭐⭐⭐⭐ + ⭐⭐⭐⭐ = berapa bintang?',
    pilihan: ['6', '7', '8', '9'],
    jawaban_benar: '8',
    penjelasan: '4 bintang ditambah 4 bintang lagi, jadi 8 bintang.',
  },
  {
    id: 'seed-b-4',
    modul: 'berhitung',
    kelas: 1,
    level: 1,
    tipe_soal: 'pilihan_ganda',
    pertanyaan: 'Ibu punya 10 🍪, kakak makan 3. Sisa berapa kue?',
    pilihan: ['6', '7', '8', '5'],
    jawaban_benar: '7',
    penjelasan: '10 kue dikurangi 3 yang dimakan, sisanya 7 kue.',
  },
  {
    id: 'seed-b-5',
    modul: 'berhitung',
    kelas: 1,
    level: 1,
    tipe_soal: 'pilihan_ganda',
    pertanyaan: '🌸🌸🌸🌸🌸 + 🌸🌸🌸🌸🌸 = berapa bunga?',
    pilihan: ['8', '9', '10', '11'],
    jawaban_benar: '10',
    penjelasan: '5 bunga ditambah 5 bunga lagi, jadi 10 bunga.',
  },

  // ===== MEMBACA — Kelas 1, Level 1 =====
  {
    id: 'seed-m-1',
    modul: 'membaca',
    kelas: 1,
    level: 1,
    tipe_soal: 'pilihan_ganda',
    pertanyaan: 'Bacalah kata di bawah ini. Apa artinya?',
    teks_bacaan: 'BUKU',
    pilihan: ['Alat untuk menulis', 'Hewan peliharaan', 'Makanan', 'Mainan'],
    jawaban_benar: 'Alat untuk menulis',
    penjelasan: 'Buku adalah alat tulis yang berisi halaman untuk dibaca atau ditulis.',
  },
  {
    id: 'seed-m-2',
    modul: 'membaca',
    kelas: 1,
    level: 1,
    tipe_soal: 'pemahaman',
    teks_bacaan: 'Budi berjalan kaki ke sekolah setiap pagi.',
    pertanyaan: 'Bagaimana Budi pergi ke sekolah?',
    pilihan: ['Naik sepeda', 'Berjalan kaki', 'Naik mobil', 'Naik bus'],
    jawaban_benar: 'Berjalan kaki',
    penjelasan: 'Di teks disebutkan "Budi berjalan kaki ke sekolah."',
  },
  {
    id: 'seed-m-3',
    modul: 'membaca',
    kelas: 1,
    level: 1,
    tipe_soal: 'pilihan_ganda',
    pertanyaan: 'Bacalah kata di bawah ini. Apa artinya?',
    teks_bacaan: 'SEKOLAH',
    pilihan: ['Tempat belajar', 'Tempat bermain', 'Tempat makan', 'Tempat tidur'],
    jawaban_benar: 'Tempat belajar',
    penjelasan: 'Sekolah adalah tempat anak-anak belajar bersama guru.',
  },
  {
    id: 'seed-m-4',
    modul: 'membaca',
    kelas: 1,
    level: 1,
    tipe_soal: 'pemahaman',
    teks_bacaan: 'Ibu memasak nasi di dapur. Aroma nasinya harum sekali.',
    pertanyaan: 'Apa yang sedang dilakukan Ibu?',
    pilihan: ['Mencuci baju', 'Memasak nasi', 'Menyapu lantai', 'Menonton TV'],
    jawaban_benar: 'Memasak nasi',
    penjelasan: 'Teks mengatakan "Ibu memasak nasi di dapur."',
  },
  {
    id: 'seed-m-5',
    modul: 'membaca',
    kelas: 1,
    level: 1,
    tipe_soal: 'pemahaman',
    teks_bacaan: 'Kucing Tono suka minum susu. Tono memberinya susu setiap pagi.',
    pertanyaan: 'Apa yang dilakukan Tono setiap pagi?',
    pilihan: ['Memberi kucing susu', 'Bermain bola', 'Menyapu halaman', 'Membaca buku'],
    jawaban_benar: 'Memberi kucing susu',
    penjelasan: 'Teks mengatakan "Tono memberinya susu setiap pagi."',
  },

  // ===== MENULIS — Kelas 1, Level 1 =====
  {
    id: 'seed-t-1',
    modul: 'menulis',
    kelas: 1,
    level: 1,
    tipe_soal: 'menyalin',
    pertanyaan: 'Salinlah huruf berikut dengan tanganmu di kanvas:',
    teks_bacaan: 'A',
    jawaban_benar: 'A',
    penjelasan: 'Pastikan huruf A ditulis dengan benar dan rapi.',
    kata_kunci: ['A', 'a'],
  },
  {
    id: 'seed-t-2',
    modul: 'menulis',
    kelas: 1,
    level: 1,
    tipe_soal: 'menyalin',
    pertanyaan: 'Salinlah kata berikut dengan tanganmu di kanvas:',
    teks_bacaan: 'MAMA',
    jawaban_benar: 'MAMA',
    penjelasan: 'Tulis kata MAMA huruf demi huruf dengan rapi.',
    kata_kunci: ['MAMA', 'mama'],
  },
  {
    id: 'seed-t-3',
    modul: 'menulis',
    kelas: 1,
    level: 1,
    tipe_soal: 'menyalin',
    pertanyaan: 'Salinlah kata berikut dengan tanganmu di kanvas:',
    teks_bacaan: 'BUKU',
    jawaban_benar: 'BUKU',
    penjelasan: 'Tulis kata BUKU huruf demi huruf dengan rapi.',
    kata_kunci: ['BUKU', 'buku'],
  },
  {
    id: 'seed-t-4',
    modul: 'menulis',
    kelas: 1,
    level: 1,
    tipe_soal: 'menyalin',
    pertanyaan: 'Salinlah kata berikut dengan tanganmu di kanvas:',
    teks_bacaan: 'SEKOLAH',
    jawaban_benar: 'SEKOLAH',
    penjelasan: 'Tulis kata SEKOLAH huruf demi huruf dengan rapi.',
    kata_kunci: ['SEKOLAH', 'sekolah'],
  },
  {
    id: 'seed-t-5',
    modul: 'menulis',
    kelas: 1,
    level: 1,
    tipe_soal: 'menyalin',
    pertanyaan: 'Salinlah huruf berikut dengan tanganmu di kanvas:',
    teks_bacaan: 'B b',
    jawaban_benar: 'B',
    penjelasan: 'Tulis huruf B besar dan kecil dengan rapi.',
    kata_kunci: ['B', 'b'],
  },
];
