import { useEffect, useState } from 'react';
import { Archive, BarChart3, BookOpen, Database, Download, FileJson, Info, Plus, RefreshCw, RotateCcw, Settings, Upload, Users } from 'lucide-react';
import { navigate } from '@/lib/router';
import { TopBar, TeacherBadge } from '@/components/TopBar';
import { Modal } from '@/components/Modal';
import * as db from '@/lib/db';
import type { Profile, ProgressEntry, Snapshot } from '@/lib/types';
import { formatDate, getModuleColor } from '@/lib/utils';

export function TeacherDashboard() {
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [selected, setSelected] = useState<Profile | null>(null);
  const [progress, setProgress] = useState<ProgressEntry[]>([]);
  const [questions, setQuestions] = useState(0);
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [showImport, setShowImport] = useState(false);
  const [notice, setNotice] = useState('');
  async function refresh() { setProfiles(await db.getAllProfiles()); setQuestions((await db.getAllQuestions()).length); setSnapshots(await db.getAllSnapshots()); }
  useEffect(() => { refresh(); }, []);
  async function selectProfile(p: Profile) { setSelected(p); setProgress(await db.getProfileProgress(p.id)); }
  function downloadData() { db.exportAllData().then(data => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `backup-rumah-belajar-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(a.href); }); }
  async function restore(snapshot: Snapshot) { if (!window.confirm('Kembalikan bank soal ke versi ini? Soal setelah tanggal snapshot akan dihapus.')) return; await db.replaceAllQuestions(snapshot.data.questions); setNotice('Bank soal berhasil dikembalikan.'); await refresh(); }
  async function handleImport(file: File) { try { const data = JSON.parse(await file.text()) as db.ExportData; if (!data.profiles || !data.questions) throw new Error('Format backup tidak lengkap.'); await db.importAllData(data); setNotice('Data berhasil dipulihkan.'); setShowImport(false); await refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : 'File tidak bisa dibaca.'); } }
  return <div className="min-h-screen bg-slate-50"><TopBar title="Ruang Guru" teacher /><main className="max-w-6xl mx-auto px-4 sm:px-6 py-7"><div className="flex flex-wrap items-center justify-between gap-3 mb-7"><div><TeacherBadge /><h1 className="text-3xl font-black text-slate-800 mt-3">Pantau perkembangan</h1><p className="text-slate-500 mt-1">Kelola murid dan materi belajar dari satu tempat.</p></div><button onClick={() => { sessionStorage.removeItem('teacherAccess'); navigate('home'); }} className="text-sm font-bold text-slate-500 hover:text-slate-800">Kunci ruang guru</button></div>
    {notice && <div className="mb-5 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-700 p-4 text-sm font-semibold">{notice}</div>}
    <div className="grid sm:grid-cols-3 gap-4 mb-7"><Metric icon={<Users />} label="Profil siswa" value={String(profiles.length)} tone="sky" /><Metric icon={<BookOpen />} label="Soal tersedia" value={String(questions)} tone="emerald" /><Metric icon={<Archive />} label="Backup soal" value={String(snapshots.length)} tone="amber" /></div>
    <div className="grid lg:grid-cols-[1fr_1.3fr] gap-5"><section className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-black text-slate-800">Daftar siswa</h2><p className="text-xs text-slate-400 mt-1">Pilih untuk melihat nilai.</p></div><button onClick={refresh} className="p-2 rounded-lg hover:bg-slate-100 text-slate-500"><RefreshCw className="w-4 h-4" /></button></div>{profiles.length === 0 ? <div className="text-center py-10 text-slate-400"><Users className="w-8 h-8 mx-auto mb-2" /><p>Belum ada profil siswa.</p></div> : <div className="space-y-2">{profiles.map(p => <button key={p.id} onClick={() => selectProfile(p)} className={`w-full flex items-center gap-3 p-3 rounded-xl text-left ${selected?.id === p.id ? 'bg-sky-50 ring-1 ring-sky-200' : 'hover:bg-slate-50'}`}><span className="text-3xl">{p.avatar}</span><span className="flex-1"><span className="block font-bold text-slate-700">{p.nama}</span><span className="block text-xs text-slate-400">Dibuat {formatDate(p.created_at)}</span></span><span className="text-sky-500">›</span></button>)}</div>}</section>
    <section className="bg-white border border-slate-200 rounded-2xl p-5">{selected ? <><div className="flex items-center gap-3 mb-5"><span className="text-4xl">{selected.avatar}</span><div><h2 className="font-black text-xl text-slate-800">{selected.nama}</h2><p className="text-sm text-slate-500">Riwayat latihan</p></div></div>{progress.length === 0 ? <div className="py-12 text-center text-slate-400"><BarChart3 className="w-9 h-9 mx-auto mb-2" /><p>Belum ada latihan yang selesai.</p></div> : <div className="space-y-2">{[...progress].reverse().map((p, i) => { const c = getModuleColor(p.modul); return <div key={`${p.completed_at}-${i}`} className="flex items-center gap-3 p-3 bg-slate-50 rounded-xl"><div className={`w-9 h-9 rounded-lg ${c.bg} ${c.text} flex items-center justify-center`}><BarChart3 className="w-4 h-4" /></div><div className="flex-1"><p className="font-bold text-sm text-slate-700 capitalize">{p.modul} · Kelas {p.kelas} Bab {p.level}</p><p className="text-xs text-slate-400">{formatDate(p.completed_at)} · {p.benar}/{p.total} benar</p></div><span className={`font-black text-lg ${p.nilai >= 70 ? 'text-emerald-600' : 'text-amber-600'}`}>{p.nilai}</span></div>; })}</div>}</> : <div className="h-full min-h-[280px] flex items-center justify-center text-center text-slate-400"><div><BarChart3 className="w-10 h-10 mx-auto mb-3" /><p className="font-semibold">Pilih nama siswa</p><p className="text-sm mt-1">Nilai dan riwayat akan tampil di sini.</p></div></div>}</section></div>
    <section className="mt-5 grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Action icon={<Plus />} title="Drop Soal" text="Tambahkan soal dengan JSON" onClick={() => navigate('drop-soal')} /><Action icon={<FileJson />} title="Prompt AI" text="Template bantu buat soal" onClick={() => navigate('ai-prompt')} /><Action icon={<Download />} title="Export data" text="Simpan backup ke file" onClick={downloadData} /><Action icon={<Upload />} title="Import data" text="Pulihkan dari backup" onClick={() => setShowImport(true)} /></section>
    <section className="mt-5 bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><Settings className="w-5 h-5 text-slate-500" /><h2 className="font-black text-slate-800">Snapshot bank soal</h2></div>{snapshots.length === 0 ? <p className="text-sm text-slate-400">Snapshot otomatis akan muncul setiap kali ada update soal.</p> : <div className="flex flex-wrap gap-2">{snapshots.slice().reverse().map(s => <div key={s.id} className="flex items-center gap-2 px-3 py-2 bg-slate-50 rounded-lg text-sm"><span className="text-slate-600">{formatDate(s.created_at)} · {s.data.questions.length} soal</span><button onClick={() => restore(s)} title="Pulihkan" className="p-1 text-amber-600 hover:bg-amber-100 rounded"><RotateCcw className="w-4 h-4" /></button></div>)}</div>}</section>
    <p className="text-xs text-slate-400 mt-5 flex items-center gap-1"><Info className="w-3.5 h-3.5" /> Soal tersimpan online di Firebase dan tersinkron antar perangkat. Profil siswa tersimpan di perangkat masing-masing.</p>
  </main><Modal open={showImport} onClose={() => setShowImport(false)} title="Import backup"><div className="text-center"><Database className="w-10 h-10 text-sky-500 mx-auto mb-3" /><p className="text-slate-600 text-sm mb-5">Pilih file backup JSON. Data di perangkat ini akan digantikan oleh data dari file.</p><label className="block w-full py-3.5 rounded-xl bg-sky-500 text-white font-bold cursor-pointer hover:bg-sky-600"><Upload className="w-4 h-4 inline mr-2" /> Pilih file JSON<input type="file" accept=".json,application/json" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) handleImport(file); }} /></label></div></Modal></div>;
}
function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: string }) { return <div className="bg-white border border-slate-200 rounded-2xl p-4 flex items-center gap-3"><div className={`w-11 h-11 rounded-xl bg-${tone}-100 text-${tone}-600 flex items-center justify-center`}>{icon}</div><div><p className="text-xs text-slate-400 font-semibold">{label}</p><p className="text-2xl font-black text-slate-800">{value}</p></div></div>; }
function Action({ icon, title, text, onClick }: { icon: React.ReactNode; title: string; text: string; onClick: () => void }) { return <button onClick={onClick} className="bg-white border border-slate-200 rounded-2xl p-4 text-left hover:border-sky-300 hover:shadow-md transition-all"><div className="text-sky-500 mb-3">{icon}</div><p className="font-black text-slate-800">{title}</p><p className="text-xs text-slate-400 mt-1">{text}</p></button>; }
